# Fonts
font_family Monolisa Nerd Font Mono
# font_family JetBrainsMono Nerd Font
bold_font auto
italic_font Maple Mono NF Italic
bold_italic_font auto
font_size 18.0

font_features MonoLisaNerdFontCompleteM-Regular +liga +ss02 +ss03

macos_colorspace displayp3

# Nerd Fonts v2.3.3
# symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6AA,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF,U+F0001-U+F1AF0 Symbols Nerd Font Mono
# Kittens
# Mappings kitty controls for windows and tabs for vim-like command
map kitty_mod+h move_window left
map kitty_mod+j move_window down
map kitty_mod+k move_window up
map kitty_mod+l move_window right
map ctrl+g kitten hints --type=linenum --linenum-action=tab nvim +{line} {path}

cursor_shape block
cursor_trail 20
background_opacity 0.80
background_blur 30

# Hide taskbar or not
hide_window_decorations titlebar-only
# macos_titlebar_color background
# hide_macos_titlebar yes

# Mouse
mouse_hide_wait 3.0

# Tab-bar
active_tab_font_style normal
inactive_tab_font_style normal
tab_bar_margin_width 7.0
tab_bar_margin_height 7.0 7.0
tab_bar_style custom
tab_bar_align center
tab_bar_edge top
tab_separator " "
tab_title_template "{fmt.bg.default}{fmt.fg._45475A}  {sup.index} 󰓩 {title}{bell_symbol}{activity_symbol}  {fmt.fg.default}"
active_tab_title_template "{fmt.bg.default}{fmt.fg._b4befe}{fmt.bg._b4befe}{fmt.fg._45475A} {sup.index} 󰓩 {title}{bell_symbol}{activity_symbol} {fmt.bg.default}{fmt.fg._b4befe}{fmt.bg.default}{fmt.fg.default}"
tab_bar_min_tabs 1
tab_bar_background none
tab_bar_margin_color none

active_tab_background   #1E1E2E
inactive_tab_background #1E1E2E

window_padding_width 2 10 5
window_margin_width 2 10 5

shell_integration no-title

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
#
# --- Overrides (MUST be after the include to win) ---
tab_bar_background none
tab_bar_margin_color none

# Make tab backgrounds match terminal background exactly
active_tab_background   #1E1E2E
inactive_tab_background #1E1E2E
